---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    kustomize.config.k8s.io/behavior: "replace"    
  name: {{ .Values.metallb.operator.operator_group.name }}
  namespace: metallb-system
spec:
  upgradeStrategy: Default
