---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/metallb-operator.metallb-system: ''
  name: metallb-operator
  namespace: metallb-system
spec:
  channel: {{ .Values.metallb.operator.channel }}
  installPlanApproval: {{ (.Values.metallb.operator.install_plan_approval) | default "Automatic" }}
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.metallb.operator.startingCSV }}